### ISSUE TITLE
Failed to load van_base_828.pth.tar

### ISSUE THREAD

**Issue by SunLoveSheep** [Visual-Attention-Network/VAN-Classification#12]
Env:
```bash
torch == 1.10.1
timm == 0.4.12
```

Script:
```python
ckpt_file = 'ckpt/van_base_828.pth.tar'
ckpt = torch.load(ckpt_file, map_location="cpu")
```

Error message:
```bash
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Since ```torch == 1.10.1``` satisfies the requirement (```torch >= 1.7```) and we do need the latest pytorch version for other parts of our project. Anyone can help? Thanks!

**Comment by Gsunshine** [comment]
Hi! I met similar issues when training VAN+HamNet (loading VAN-Large).
 
Some corruption in your checkpoint possibly causes it. I download the checkpoint again, and the problem disappears. 

My env is `torch == 1.10.3`, the latest version.

**Comment by SunLoveSheep** [comment]
@Gsunshine  Thanks. I download the save checkpoint file again from Tsinghua Cloud and it loaded without complains.
