### ISSUE TITLE
When to use the freeze_patch_emb method

### ISSUE THREAD

**Issue by exiawsh** [Visual-Attention-Network/VAN-Classification#14]
Hello, I have doubt about when to use the freeze_patch_emb function, did you freeze the param when you train your model?

**Comment by exiawsh** [comment]
There are also questions about the design of  layer_scale.https://github.com/Visual-Attention-Network/VAN-Classification/blob/d94f1568a25bbfbf2902368675f081e8e65399da/models/van.py#L96 After the training, its operation belongs to a static process. What is its original design intention? Why not use a structure similar to SENet to dynamically determine the weight?

**Comment by MenghaoGuo** [comment]
We adopte the same strategy with [this paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Touvron_Going_Deeper_With_Image_Transformers_ICCV_2021_paper.pdf).

In practice, we found we can achieve better results with dynamic weights, but it introduced some additional computational and memory overhead

**Comment by exiawsh** [comment]
> We adopte the same strategy with [this paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Touvron_Going_Deeper_With_Image_Transformers_ICCV_2021_paper.pdf).
> 
> In practice, we found we can achieve better results with dynamic weights, but it introduced some additional computational and memory overhead

thx
