### ISSUE TITLE
Question related to permutation operation used in the model

### ISSUE THREAD

**Issue by Vandermode** [Visual-Attention-Network/VAN-Classification#15]
Hi, it looks like all the dimension permutation operations on PatchEmbed and Block are unnecessary, making the whole network a convolutional neural network rather than a transformer.  Is that true? I was wondering your opinion on this argument. Thanks:)

**Comment by MenghaoGuo** [comment]
Hi,

Since VAN adopts both BN and LN, we take this permutation operations to make LN work normally.
