### ISSUE TITLE
Issue about training

### ISSUE THREAD

**Issue by annwfsly** [Visual-Attention-Network/VAN-Classification#20]
I have tried to train VAN-Classification on ImageNet as README does, but I find the top1 acc converges in 56% in stead of 75.4% . ( I trained on 1 GPU in stead of 8 GPUs, could this influence the result ? )
![微信图片_20220319094616](https://user-images.githubusercontent.com/46639141/159102143-1f9bde7b-822e-4b8b-965c-a48e4cdef587.png)

**Comment by MenghaoGuo** [comment]
Yes,  the training accuracy is related to the training epochs and batch size.

**Comment by annwfsly** [comment]
> Yes, the training accuracy is related to the training epochs and batch size.

Thank U，it has reached 74.5% at 310 epoch, and I guess the lost acc may be caused by my limited GPU number.
