### ISSUE TITLE
The model used for classification problem

### ISSUE THREAD

**Issue by xwhkkk** [Visual-Attention-Network/VAN-Classification#21]
Hello ! what's the model you used for the classification problem? I know the VANs is the backbone, the `train.py` indicates the model default is ResNet?

**Comment by wgqhandsome** [comment]
> 

Hello! Can you run this code on your own dataset?

**Comment by xwhkkk** [comment]
> > 
> 
> Hello! Can you run this code on your own dataset?

I haven't run this code yet. I will try as soon as possible
