### ISSUE TITLE
OverlapPatchEmbed

### ISSUE THREAD

**Issue by hbw945** [Visual-Attention-Network/VAN-Classification#22]
For classification，can you tell me the total GPU usage about the base version，Thanks！

**Comment by hbw945** [comment]
For train

**Comment by hbw945** [comment]
Do you think different training strategies have a great impact on van？Thanks！

**Comment by MenghaoGuo** [comment]
Due to limited computational resource, we did not change the training hyperparameters and training strategies.

**Comment by hbw945** [comment]
What are the H and W obtained by overlappatchembed for, and numpatch doesn't seem to be used. Maybe my ability is limited and I didn't see it. Thank you！

**Comment by MenghaoGuo** [comment]
Yes, i remove it.
