### ISSUE TITLE
Why not use SyncBN

### ISSUE THREAD

**Issue by Holidays1999** [Visual-Attention-Network/VAN-Classification#23]
Thanks for your amazing work!It converges fastly and get amazing accuracy on imagenet.
In your pth file, I found args.sync_bn is False.
In your train.py, I found the model  in your code broadcast buffers about bn before each forward instead of SyncBN.
So, I have a small question, why don't you use SyncBN?
Thanks very much!

**Comment by MenghaoGuo** [comment]
Good question. 

We ignored SyncBN and did not conduct this experiment.
I think it will improve the performance of the model.
I am going to try it now.

Thanks for your question and kind advice.

**Comment by Holidays1999** [comment]
Thanks for your reply~
hoping SyncBN can achieve higher accuracy
