### ISSUE TITLE
found reduplicated shortcut connections for the same attention module

### ISSUE THREAD

**Issue by Karbo123** [Visual-Attention-Network/VAN-Classification#4]
Firstly many thanks to this great work. However, I find something weird in the codes, but I don't know whether it is intentional. 

I find that SpatialAttention already has a shortcut connection in its [forward function](https://github.com/Visual-Attention-Network/VAN-Classification/blob/main/models/van.py#L82), but I also find another shortcut connection in [Block's forward function](https://github.com/Visual-Attention-Network/VAN-Classification/blob/main/models/van.py#L120). I think that the shortcuts are reduplicated twice for the same attention module, it should be better to remove the first residual connection [here](https://github.com/Visual-Attention-Network/VAN-Classification/blob/main/models/van.py#L82).

Please point out any possible mistakes in my comments, thanks.

**Comment by MenghaoGuo** [comment]
Thanks for your attention to our work.

Careful observation.

In fact, it  is not a redundancy. In the experimen, we find that it can improve training stability and final result by adding a  residual connection. It is also written in experiment section. 

![image](https://user-images.githubusercontent.com/38318671/155834751-1017b1c0-99a5-4499-9d4e-6954ac003bed.png)

**Comment by Karbo123** [comment]
Thanks for the quick reply. I initially think it is a mistake, but now  I know it is written on purpose.
However, I still think that the trick is rather elusive, and hard to understand.
