### ISSUE TITLE
Question about semantic segmentation

### ISSUE THREAD

**Issue by annwfsly** [Visual-Attention-Network/VAN-Classification#8]
Thanks for publishing such an excellent work ! It will be perfect if you could provide the semantic segmentation version. Really appreciate for your help !

**Comment by MenghaoGuo** [comment]
For segmentation 

Requirement: 

Pytorch >= 1.7
MMSegmentation == v0.12.0 (https://github.com/open-mmlab/mmsegmentation/tree/v0.12.0)
