### ISSUE TITLE
Unstable as backbone for semantic segmentation

### ISSUE THREAD

**Issue by shkarupa-alex** [Visual-Attention-Network/VAN-Classification#9]
I've tried to use Van Large as backbone for binary semantic segmentation and found it very unstable.

Model: UpperNet. Previously well tested with Resnet50 and SwinBase.
Features: same as in https://github.com/Visual-Attention-Network/VAN-Segmentation

Just switching backbone to van large fails after 5 of 7 epochs: model generate nan outputs.
In the same time F1 and accuracy grows from 1 to 5 epochs (this is not a divergency).

Right now i have no time to dive deeper to find nan's source, so this is just a feedback.

**Comment by Andy1621** [comment]
@shkarupa-alex  Such phenomenon is common in the transformer-style backbones. You can find the issue in [DeiT](https://github.com/facebookresearch/deit/issues/29). 
In my experiments, layer scale sometimes causes this unstable training, which is used in VAN.
https://github.com/Visual-Attention-Network/VAN-Classification/blob/d94f1568a25bbfbf2902368675f081e8e65399da/models/van.py#L97-L100

Maybe you can try our [UniFormer](https://github.com/Sense-X/UniFormer), we have avoided some tricks that cause unstable training and all models/configs/logs are released.

**Comment by MenghaoGuo** [comment]
Thanks all.

We do not find this problem in the traning process. We'll explore it, if we have time.
